package io.quarkus.amazon.dynamodb.enhanced.runtime;

import java.util.List;
import java.util.Optional;

import io.quarkus.runtime.annotations.ConfigDocSection;
import io.quarkus.runtime.annotations.ConfigItem;
import io.quarkus.runtime.annotations.ConfigPhase;
import io.quarkus.runtime.annotations.ConfigRoot;

@ConfigRoot(name = "dynamodbenhanced", phase = ConfigPhase.BUILD_AND_RUN_TIME_FIXED)
public class DynamoDbEnhancedBuildTimeConfig {

    /**
     * Extension of the DynamodbEnhancedClient
     */
    @ConfigItem
    @ConfigDocSection
    Optional<List<DynamodbEnhancedClientExtension>> clientExtensions = Optional
            .of(List.of(DynamodbEnhancedClientExtension.VersionedRecordExtension,
                    DynamodbEnhancedClientExtension.AutoGeneratedTimestampRecordExtension));

    public enum DynamodbEnhancedClientExtension {
        VersionedRecordExtension,
        AtomicCounterExtension,
        AutoGeneratedTimestampRecordExtension

    }
}
