package io.quarkus.amazon.dynamodb.enhanced.runtime;

import io.quarkus.arc.runtime.BeanContainer;
import io.quarkus.arc.runtime.BeanContainerListener;
import io.quarkus.runtime.annotations.Recorder;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClientExtension;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AtomicCounterExtension;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.enhanced.dynamodb.extensions.VersionedRecordExtension;
import software.amazon.awssdk.enhanced.dynamodb.internal.client.ExtensionResolver;
import software.amazon.awssdk.services.dynamodb.DynamoDbAsyncClient;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;

import java.util.ArrayList;
import java.util.List;

@Recorder
public class DynamodbEnhancedClientRecorder {

    DynamoDbEnhancedBuildTimeConfig buildTimeConfig;

    public DynamodbEnhancedClientRecorder(DynamoDbEnhancedBuildTimeConfig buildTimeConfig) {
        this.buildTimeConfig = buildTimeConfig;
    }

    public BeanContainerListener setDynamoDbClient() {
        BeanContainerListener beanContainerListener = new BeanContainerListener() {

            @Override
            public void created(BeanContainer container) {
                DynamodbEnhancedClientProducer producer = container.beanInstance(DynamodbEnhancedClientProducer.class);
                producer.setDynamoDbClient(container.beanInstance(DynamoDbClient.class),
                        createExtensionList());
            }
        };

        return beanContainerListener;
    }

    public BeanContainerListener setDynamoDbAsyncClient() {
        BeanContainerListener beanContainerListener = new BeanContainerListener() {

            @Override
            public void created(BeanContainer container) {
                DynamodbEnhancedClientProducer producer = container.beanInstance(DynamodbEnhancedClientProducer.class);
                producer.setDynamoDbAsyncClient(container.beanInstance(DynamoDbAsyncClient.class),
                        createExtensionList());
            }
        };

        return beanContainerListener;
    }

    private List<DynamoDbEnhancedClientExtension> createExtensionList() {
        if (this.buildTimeConfig.clientExtensions != null && this.buildTimeConfig.clientExtensions.isPresent() && !this.buildTimeConfig.clientExtensions.get().isEmpty()) {
            List<DynamoDbEnhancedClientExtension> extensionsList = new ArrayList<>();
            for (var extension : this.buildTimeConfig.clientExtensions.get()) {
                switch (extension) {
                    case AtomicCounterExtension:
                        extensionsList.add(AtomicCounterExtension.builder().build());
                        break;
                    case VersionedRecordExtension:
                        extensionsList.add(VersionedRecordExtension.builder().build());
                        break;
                    case AutoGeneratedTimestampRecordExtension:
                        extensionsList.add(AutoGeneratedTimestampRecordExtension.create());
                        break;
                }
            }
            return extensionsList;
        }
        return ExtensionResolver.defaultExtensions();
    }
}
